### ISSUE TITLE
delete_duplicates doesn't handle ascii coding properly (on Linux)

### ISSUE THREAD

**Issue by Nadelbaum** [simokivimaki/viihdepython#5]
print('Processing:', key[0], ';', key[1])

Should be changed to:

print('Processing:', key[0].encode('utf-8'), ';', key[1].encode('utf-8'))

And 

print('Found duplicates for:', key[0], ';', key[1])

Should be changed to:

print('Found duplicates for:', key[0].encode('utf-8'), ';', key[1].encode('utf-8'))

Otherwise, at least on a Raspberry Pi 3 (vanilla installation), when used through a cron job the following error is received if the program names contain "illegal" characters:

UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 1: ordinal not in range(128)

**Comment by simokivimaki** [comment]
I assume you know Finnish?

Viihdepython tulostaa tarkoituksella unicode-stringejä konsoliin. Jos ne muutettaisiin encode-metodilla bytes-tyyppiseksi utf-8-dataksi, niin eri ympäristöissä ääkköset menisivät hyvinkin mahdollisesti rikki.

Parempi ratkaisu on varmistaa, että oman ympäristösi python osaa tulostaa unicodea suoraan oikein. Tarkista ensin mitä `locale` tulostaa. Pi 3 taitaa käyttää Debiania, joten `sudo update-locale LC_CTYPE="en_US.UTF-8"` pitäisi toimia. Joissain Debian-asennuksissa LC_CTYPE-arvo on oletuksena väärin pelkkä UTF-8.

Vaihtoehtoisesti voit kokeilla `export PYTHONIOENCODING=UTF-8` ympäristömuuttujan asettamista.

Kerro saatko ongelman ratkaistua tällä tavoin ilman koodimuutoksia.

**Comment by Nadelbaum** [comment]
Moi,Alkuperäinen koodi toimii kyllä normiterminaalista, mutta cronin kautta ajettuna ei. En ole debugannut sen enempää, että mikä ero, kun locale on kuitenkin oikea.Joka tapauksessa tämä toimii tuolla koodimuutosehdotuksellani, joten se riittää omaan tarpeeseeni. T. Antti28.3.2017 21.53 Simo Kivimäki <notifications@github.com> kirjoitti:I assume you know Finnish?
Viihdepython tulostaa tarkoituksella unicode-stringejä konsoliin. Jos ne muutettaisiin encode-metodilla bytes-tyyppiseksi utf-8-dataksi, niin eri ympäristöissä ääkköset menisivät hyvinkin mahdollisesti rikki.
Parempi ratkaisu on varmistaa, että oman ympäristösi python osaa tulostaa unicodea suoraan oikein. Tarkista ensin mitä locale tulostaa. Pi 3 taitaa käyttää Debiania, joten sudo update-locale LC_CTYPE="en_US.UTF-8" pitäisi toimia. Joissain Debian-asennuksissa LC_CTYPE-arvo on oletuksena väärin pelkkä UTF-8.
Vaihtoehtoisesti voit kokeilla export PYTHONIOENCODING=UTF-8 ympäristömuuttujan asettamista.
Kerro saatko ongelman ratkaistua tällä tavoin ilman koodimuutoksia.

**Comment by simokivimaki** [comment]
Ok, luultavasti cron poimii eri ympäristöasetukset kuin terminaali. Tätä olisi voinut tutkia katsomalla mitä cronin ajamana `locale` tulostaa. Tai sitten python käsittelee tilanteen eri tavalla, kun tuloste ohjataan tiedostoon/sähköpostiin.
